language: cpp
#sudo: false
git:
  depth: 1
services:
  - docker
#matrix:
#  include:
#    - os: linux
#      compiler: gcc
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['g++-7', 'libstdc++6', 'libstdc++-6-dev', 'libstdc++6-dbg']

before_script:
  - docker pull ubuntu:16.04
  - echo 'Configure...' && echo -en 'travis_fold:start:script.configure\\r'
  - docker wget http://pol.uo.hyeah.pl/upload/core/polserver099-LINUX-2018-02-09.zip
  - docker unzip polserver099-LINUX-2018-02-09.zip
  - docker cp -Rf polserver099-LINUX-2018-02-09/* .
  - docker echo "ModuleDirectory=scripts" >>scripts/ecompile.cfg
  - docker echo "IncludeDirectory=scripts" >>scripts/ecompile.cfg
  - docker echo "PolScriptRoot=scripts" >>scripts/ecompile.cfg
  - docker echo "PackageRoot=pkg" >>scripts/ecompile.cfg
  - docker echo -en 'travis_fold:end:script.configure\\r'

script:
  - docker echo 'Build...' && echo -en 'travis_fold:start:script.build\\r'
  - docker scripts/ecompile -AT
  - docker echo -en 'travis_fold:end:script.build\\r'


notifications:
  email:
    #    - polteam@polserver.com
